("LWIDEA.DGO"
 ("tpage-2929.go"
  "tpage-2930.go"
  "citizen-fat-ag.go"
  "citizen-norm-ag.go"
  "crimson-guard-ag.go"
  "citizen-chick-ag.go"
  "hellcat-ag.go"
  "carc-ag.go"
  "cara-ag.go"
  "carb-ag.go"
  "citizen-norm-rider-ag.go"
  "crimson-bike-ag.go"
  "bikec-ag.go"
  "bikeb-ag.go"
  "bikea-ag.go"
  "tpage-2438.go" ;; added (MOD paddywagon/traffic) -- lmeetbrt-pris, the paddy-wagon textures
  "paddy-wagon-ag.go" ;; added (MOD paddywagon/traffic) -- see jak2_config.jsonc extra_art_groups_by_dgo
  "lwidea.go"
 ))
